### ISSUE TITLE
Still Supported?

### ISSUE THREAD

**Issue by michaeljohnbarr** [kura/yarg#5]
@kura - Just seeing if this is still supported. I see a pull request from May 12, 2015 and there have been no updates in the past 2 years. https://kura.io is down, so my assumption is that kura@kura.io will not work to contact you.

I am wanting to contribute some updates to this package (as well as use it in an upcoming project), which is why I ask.

**Comment by kura** [comment]
Hey, it is sort of still supported. I'm busy with life and whatnot and totally flaked out.
